title: IFTIKHAR SHAH
#logo: iftikharshah.github.io/asset/IMG_20231124_133555_376.jpg
description: An individual with the knowledge and skills of Data Warehousing and analytical skills of Power BI, Tableau loves encountering problems and working out the most appropriate solutions. In addition, I am detail-oriented and self-motivated looking forward to connecting with an esteemed organization to utilize my skill set.
show_downloads: false
theme: jekyll-theme-minimal
